### ISSUE TITLE
Reporting spans with JaegerHttpTransport fails with ObjectDisposedException

### ISSUE THREAD

**Issue by cwe1ss** [jaegertracing/jaeger-client-csharp#52]
This seems to happen after a few sends or after a few seconds. I was using a batch size of 3.

I will probably have time to look at this in the next 1-3 days but if anyone wants to jump in, feel free to do so and just let me know in the comments.

```
fail: Jaeger.Core.Reporters.RemoteReporter[0]
      Unable to report span in RemoteReporter
Thrift.Transports.TTransportException: Couldn't connect to server: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.StreamHelpers.ValidateCopyToArgs(Stream source, Stream destination, Int32 bufferSize)
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<InternalSendRequestBodyAsync>d__131.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thrift.Transports.Client.THttpClientTransport.<FlushAsync>d__21.MoveNext() in C:\projects\jaeger-client-csharp\src\Thrift\netcore\Thrift\Transports\Client\THttpClientTransport.cs:line 178
   at Thrift.Transports.Client.THttpClientTransport.<FlushAsync>d__21.MoveNext() in C:\projects\jaeger-client-csharp\src\Thrift\netcore\Thrift\Transports\Client\THttpClientTransport.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jaeger.Transport.Thrift.Transport.Sender.JaegerThriftHttpSender.<SendAsync>d__2.MoveNext() in C:\projects\jaeger-client-csharp\src\Jaeger.Transport.Thrift\Transport\Sender\JaegerThriftHTTPSender.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jaeger.Transport.Thrift.Transport.Sender.JaegerSender.<FlushAsync>d__9.MoveNext() in C:\projects\jaeger-client-csharp\src\Jaeger.Transport.Thrift\Transport\Sender\JaegerSender.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jaeger.Transport.Thrift.Transport.JaegerHttpTransport.<ProtocolAppendLogicAsync>d__8.MoveNext() in C:\projects\jaeger-client-csharp\src\Jaeger.Transport.Thrift\Transport\JaegerHTTPTransport.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jaeger.Transport.Thrift.Transport.JaegerThriftTransport.<AppendAsync>d__5.MoveNext() in C:\projects\jaeger-client-csharp\src\Jaeger.Transport.Thrift\Transport\JaegerThriftTransport.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jaeger.Core.Reporters.RemoteReporter.<Report>d__5.MoveNext() in C:\projects\jaeger-client-csharp\src\Jaeger.Core\Reporters\RemoteReporter.cs:line 46
```

**Comment by cwe1ss** [comment]
Quick note: I haven't yet had this behavior with #55 so this should be resolved if we merge that PR.

**Comment by Falco20019** [comment]
Something that we should check again now that #55 is merged. The assumption is that it‘s gone.

**Comment by cwe1ss** [comment]
Yes, I couldn't reproduce it with the current code.
